/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 burguer.gltf 
Author: erebus3d (https://sketchfab.com/erebus3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/burger-realistic-free-18e59d7dbd2243c69f469e0f056f44c4
Title: Burger Realistic (Free)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BurgerModel(props) {
  const { nodes, materials } = useGLTF('/burger.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.027}>
        <mesh geometry={nodes.bun_bun001_0.geometry} material={materials['bun.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.vegeis_vegies001_0.geometry} material={materials['vegies.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.pPlane14_lettuce001_0.geometry} material={materials['lettuce.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.pPlane15_lettuce001_0.geometry} material={materials['lettuce.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.pPlane16_lettuce001_0.geometry} material={materials['lettuce.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.pPlane17_lettuce001_0.geometry} material={materials['lettuce.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload("/burger.gltf")
